# Generated by Django 3.1.5 on 2021-01-26 15:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proplistapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postad',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
